[package]
name = "env-replace"
version = "0.1.0"
authors = ["Nicolas Barbotte <nicolas@barbotte.net>"]

[dependencies]
colored = "1.6.1"
dotenv = "0.13.0"
regex = "1.0.4"
structopt = "0.2.10"

[profile.release]
lto = true
